config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :sessions
  resources :users
  resources :locations
  resources :families
  resources :students
  resources :registrations
  resources :camp_instructors

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/financial', to: 'home#financial', as: :financial


  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  
  # set the root url
  root to: 'home#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  include ChessCampHelpers

  # relationships
  belongs_to :family
  has_many :registrations
  has_many :camps, through: :registrations

  # validations
  validates_presence_of :family_id, :first_name, :last_name
  ratings_array = [0] + (100..3000).to_a
  validates :rating, numericality: { only_integer: true, allow_blank: true }, inclusion: { in: ratings_array, allow_blank: true }  
  validates_date :date_of_birth, :before => lambda { Date.today }, :before_message => "cannot be in the future", allow_blank: true, on: :create
  validate :family_is_active_in_the_system, on: :create

  # scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :below_rating, ->(ceiling) { where('rating < ?', ceiling) }
  scope :at_or_above_rating, ->(floor) { where('rating >= ?', floor) }

  # callbacks
  before_destroy :is_never_destroyable

  # other methods
  def name
    "#{self.last_name}, #{self.first_name}"
  end

  def proper_name
    "#{self.first_name} #{self.last_name}"
  end

  def age
    return nil if date_of_birth.blank?
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end

  def make_inactive
    self.active = false
    self.save!
  end

  private
  def family_is_active_in_the_system
    is_active_in_system(:family)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  authorize_resource
  def index
    @active_students = Student.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_students = Student.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    @regs=@student.registrations
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: "#{@student.proper_name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: "#{@student.proper_name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @student.destroy
    redirect_to students_url, alert: "#{@student.proper_name} cannot be removed from the system."
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :family_id, :date_of_birth,:rating,:active)
    end
end

app/views/students/_active_students.html.erb
<h3>Active Students</h3>

<table >
  <thead>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Rating</th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @active_students.each do |student| %>
  <tr>
    <td><%= link_to student.name, student_path(student) %></td>
    <td><%= student.age%></td>
    <td><%= student.rating==0 ? "Unrated" : student.rating%></td>
    <td><%= link_to 'Edit', edit_student_path(student)%></td>
  </tr>
<% end %>
</tbody>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @active_students, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/students/_cannot_save.html.erb
<%  if @student.errors.any? %>
<div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning radius">
    <a href="#" class="close">&times;</a>
<h3><%= pluralize(@student.errors.count, "error")%> prohibited this student from being saved:</h3>
      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
</div>
<% end %>

app/views/students/_form.html.erb
<%= simple_form_for(@student, html: { class: 'form-horizontal' }) do |f| %>
    <div class="row">
    <div class="small-3 columns">
    <%= f.input :first_name %>
    </div>
    <div class="small-3 columns end">
    <%= f.input :last_name %>
    </div>
    </div>
    <div class="row">
    <div class="small-3 columns">
    <%= f.input :family_id, collection: Family.active.alphabetical, prompt: "Select family...", label_method: :family_name %>
    </div>
    <div class="small-3 columns end">
    <%= f.input :date_of_birth, as: :string, input_html: {:class => "avg datepicker"}  %>
    </div>
    </div>
    <div class="row">
    <div class="small-2 columns">
    <%= f.input :rating %>
    </div>
    <div class="small-2 columns end">
    </br>
</br>
    <%= f.input :active %>
    </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of students', students_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/students/_inactive_students.html.erb
<% unless @inactive_students.empty? %>
  <h3>&nbsp;</h3>
  <div class="panel clearfix">
    <h5>Inactive Students</h5>
    <ul class="side-nav">
      <% @inactive_students.each do |student| %>
        <li><%= link_to student.name, student_path(student) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/students/_student_details.html.erb
<p>
<strong>Student Name:&nbsp;</strong> 
  <%= @student.first_name%>
  <%= link_to @student.last_name, family_path(@student.family) %>
</p>
<p>
<strong>Birthday:&nbsp;</strong> 
  <%= "#{@student.date_of_birth.strftime('%m/%d/%Y')}" %>
</p>
<p>
<strong>Age:&nbsp;</strong> 
  <%= @student.age %>
</p>
<p>
<strong>Rating:&nbsp;</strong> 
  <%= @student.rating==0 ? "Unrated" : @student.rating%>
</p>
<p>
<strong>Active?&nbsp;</strong>
  <%= @student.active ? "Yes" : "No" %>
</p>

app/views/students/_student_registrations.html.erb
<% unless @regs.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Registrations for this student</h5>
    <ul class="side-nav">
      <% @regs.each do |registration| %>
        <li><%= link_to registration.camp.name, camp_path(registration.camp)%><%="#{registration.camp.start_date.strftime('%m/%d/%y')}"%></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>No Registrations</h5>
  </div>
<% end %>

app/views/students/_students_registrations.html.erb
<% unless @student.registrations.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Registrations for this student</h5>
    <ul class="side-nav">
      <% @student.registrations.each do |registration| %>
        <li><%= link_to student.name, student_path(student) %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>No Students</h5>
  </div>
<% end %>

app/views/students/edit.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>Edit Student</h1>
   	</div>
  </div>
</div>
<%=render 'cannot_save'%>
</br>
<div class="row">
<div class ="small-12 colums">
<%= render 'form' %>
</div>

app/views/students/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "student", 
                                                         primary: "active_students", 
                                                         secondary: nil, 
                                                         sidebar: "inactive_students"} %>

app/views/students/new.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>New Student</h1>
   	</div>
  </div>
</div>
<%=render 'cannot_save'%>
</br>
<div class="row">
<div class ="small-12 colums">
<%= render 'form' %>
</div>
</div>

app/views/students/show.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-8 colums">
    <h1>Student Details</h1>
    </div>
  </div>
</div>
<%= render :partial => "partials/flash" %>
</br>
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "student_details" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'student_registrations' %>
  </div>
</div>
<div class="row">
<%= render partial: "partials/object_options", locals: {model_name: "student", object: @student}  %>
</div>