config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :sessions
  resources :users
  resources :locations
  resources :families
  resources :students
  resources :registrations
  resources :camp_instructors

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/financial', to: 'home#financial', as: :financial


  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  
  # set the root url
  root to: 'home#index'

end

app/models/camp.rb
class Camp < ActiveRecord::Base
  include ChessCampHelpers

  # relationships
  belongs_to :curriculum
  has_many :camp_instructors
  has_many :instructors, through: :camp_instructors
  belongs_to :location
  has_many :registrations
  has_many :students, through: :registrations

  # validations
  validates_presence_of :curriculum_id, :time_slot, :start_date
  validates_numericality_of :cost, only_integer: true, greater_than_or_equal_to: 0
  validates_date :start_date, :on_or_after => lambda { Date.today }, :on_or_after_message => "cannot be in the past", on:  :create
  validates_date :end_date, :on_or_after => :start_date
  validates_inclusion_of :time_slot, in: %w[am pm], message: "is not an accepted time slot"
  validates_numericality_of :max_students, only_integer: true, greater_than: 0, allow_blank: true
  validate :curriculum_is_active_in_the_system
  validate :location_is_active_in_the_system
  validate :camp_is_not_a_duplicate, on: :create
  validate :max_students_not_greater_than_capacity
  validate :camp_can_be_deactivated

  # scopes
  scope :alphabetical, -> { joins(:curriculum).order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :chronological, -> { order('start_date','end_date') }
  scope :morning, -> { where('time_slot = ?','am') }
  scope :afternoon, -> { where('time_slot = ?','pm') }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }
  scope :past, -> { where('end_date < ?', Date.today) }
  scope :for_curriculum, ->(curriculum_id) { where("curriculum_id = ?", curriculum_id) }

  # instance methods
  def name
    self.curriculum.name
  end

  def already_exists?
    Camp.where(time_slot: self.time_slot, start_date: self.start_date, location_id: self.location_id).size == 1
  end

  # class methods
  def self.openings
    Camp.active.chronological.to_a.select{|c| c.registrations.size < c.max_students}
  end

  # callbacks
  before_destroy :verify_that_there_are_no_registrations_for_camp
  before_update :remove_instructors_from_inactive_camp

  # private
  def curriculum_is_active_in_the_system
    is_active_in_system(:curriculum)
  end

  def location_is_active_in_the_system
    is_active_in_system(:location)
  end

  def camp_is_not_a_duplicate
    return true if self.time_slot.nil? || self.start_date.nil? || self.location_id.nil?
    if self.already_exists?
      errors.add(:time_slot, "already exists for start date, time slot and location")
    end
  end

  def verify_that_there_are_no_registrations_for_camp
    self.registrations.to_a.empty?
  end

  def camp_can_be_deactivated
    return true if self.active
    unless verify_that_there_are_no_registrations_for_camp
      errors.add(:base, "Camp cannot be inactive because there are students registered")
      return false
    end
    return true
  end

  def max_students_not_greater_than_capacity
    return true if self.max_students.nil? || self.location_id.nil?
    if self.max_students > self.location.max_capacity
      errors.add(:max_students, "is greater than the location capacity")
    end
  end

  def remove_instructors_from_inactive_camp
    # confirm that no registrations for camp and camp is marked as inactive
    if verify_that_there_are_no_registrations_for_camp && !self.active
      self.camp_instructors.each{|ci| ci.destroy}
    end
  end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]
  authorize_resource
  def index
    @upcoming_camps = Camp.upcoming.active.chronological.paginate(:page => params[:page]).per_page(10)
    @past_camps = Camp.past.chronological.paginate(:page => params[:page]).per_page(10)
    @inactive_camps = Camp.inactive.alphabetical.to_a
  end

  def show
    @instructors = @camp.instructors.alphabetical.to_a
    @regs=@camp.registrations.by_student
    @registration=Registration.new
  end

  def new
    @camp = Camp.new
  end

  def edit
  end

  def create
    @camp = Camp.new(camp_params)
    if @camp.save
      redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @camp.update(camp_params)
      redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    if @camp.destroy
    redirect_to camps_url, notice: "#{@camp.name} camp on #{@camp.start_date.strftime('%m/%d/%y')} was removed from the system."
    else
    redirect_to camps_url, alert: "#{@camp.name} camp on #{@camp.start_date.strftime('%m/%d/%y')} cannot be removed from the system."
    end
  end

  private
    def set_camp
      @camp = Camp.find(params[:id])
    end

    def camp_params
      params.require(:camp).permit(:curriculum_id, :location_id,:cost, :start_date, :end_date, :time_slot, :max_students, :active, :instructor_ids => [],:student_ids=>[])
    end
end

app/views/camps/_camp_details.html.erb
<p>
<strong>Name:&nbsp;&nbsp;</strong> 
  <%= link_to @camp.name, curriculum_path(@camp.curriculum) %>
</p>
<p>
<strong>Cost:&nbsp;&nbsp;</strong> 
  <%= number_to_currency(@camp.cost) %>
</p>
<p>
<strong>Max Students:&nbsp;&nbsp;</strong> 
  <%= @camp.max_students %>
</p>
<p>
<strong>Dates:&nbsp;&nbsp;</strong> 
  <%= @camp.start_date.strftime('%m/%d/%y') %> 
  <% if @camp.start_date != @camp.end_date %>
    <%= "- #{@camp.end_date.strftime('%m/%d/%y')}" %>
  <% end %>
</p>
<p>
<strong>Time:&nbsp;&nbsp;</strong> 
  <%= @camp.time_slot == "am" ? "Morning" : "Afternoon" %>
</p>

<p>
<strong>Location:&nbsp;&nbsp;</strong> 
  <%= link_to @camp.location.name, location_path(@camp.location) %>
</p>

<% if logged_in? && current_user.role == "admin" %>
<p>
<strong>Active?&nbsp;&nbsp;</strong>
  <%= @camp.active ? "Yes" : "No" %>
</p>
<div id="dialog" title="Financial Report">
  <ul class="pricing-table">
    <li class="title">Full Payment</li>
    <%@camp.registrations.paid.each do |reg| %>
    <li class="bullet-item"><%=reg.student.name%></li>
    <%end%>
    <li class="price">Amount Received: $<%=@camp.registrations.paid.count*@camp.cost+@camp.registrations.deposit_only.count*50%></li>
    <li class="title">Deposit</li>
    <%@camp.registrations.deposit_only.each do |reg| %>
    <li class="bullet-item"><%=reg.student.name%></li>
    <%end%>
    <li class="price">Amount Due: $<%=@camp.registrations.deposit_only.count*(@camp.cost-50)%></li>
    <p>-------------------------------------------------</p>
     <li class="price">Total $<%=@camp.registrations.count*@camp.cost%></li>
  </ul>
</div>
 
<button id="opener">Financial Report</button>
<%end%>

app/views/camps/_camp_financial_report.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>Camp Financial Report</h1>
   	</div>
  </div>
</div>
<%=render 'cannot_save'%>
</br>
<div class="row">
<div class ="small-12 colums">
<%= render 'form' %>
</div>
</div>

app/views/camps/_camp_instructors.html.erb
<% unless @instructors.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel-sid">
    <h5>Camp Instructors</h5>
    <ul>
      <% @instructors.each do |instructor| %>
        <li><%= link_to instructor.name, instructor_path(instructor) %></li>
      <% end %>
    </ul>

<% else %>
  <div class="panel clearfix">
    <h5>No Instructors</h5>
  </div>
<% end %>
</div>

</br>
<% unless @camp.registrations.empty? %>

<h5>Registrations (<%=@regs.count%>)</h5>
<table>
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Rating</th>
      <th>Age</th>
      <% if logged_in? && current_user.role == "admin" %>
      <th>Edit</th>
      <th>Destroy</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @regs.each do |reg| %>
      <tr>
        <% if logged_in? %>
        <td><%= link_to reg.student.name, student_path(reg.student) %></td>
        <% else %>
        <td><%= reg.student.name %></td>
        <%end%>
        <td><%= reg.student.rating==0 ? "Unrated" : reg.student.rating%></td>
        <td><%= reg.student.age%></td>
        <% if logged_in? && current_user.role == "admin" %>
          <td><%= link_to(edit_registration_path(reg), :camp_id=>@camp.id, class: 'button tiny radius') do%>Edit</td>
        <% end %>
        <td><%= link_to(registration_path(reg), method: 'delete', data: { confirm: "Are you sure you want to destroy this registration?" }, class: 'button tiny radius alert') do %>
            &nbsp;Destroy</td>
            <%end%>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if logged_in? && current_user.role == "admin" %>

<div class="row">
  <div class="small-8 columns">
    &nbsp;
  </div>
  <div class="small-4 columns">
 <%= link_to 'Add registration ', new_registration_path(:id => @camp.id),class:"button tiny radius primary"%> 
</div>
</div>
<%end%>
<%end%>

app/views/camps/_camps.html.erb
<h3><%= status %> Camps</h3>

<table class="table">
  <tr>
    <th width="260">Name</th>
    <th width="120">Start On</th>
    <th width="120">Time</th>
    <th></th>
    <th></th>
  </tr>

<% camps.each do |camp| %>
  <tr>
    <td><%= link_to camp.name, camp_path(camp) %></td>
    <td align="center"><%= camp.start_date.strftime('%m/%d/%y') %></td>
    <td align="center"><%= camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
    <td><%= link_to 'Edit', edit_camp_path(camp), class: "button tiny radius" %></td>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/camps/_cannot_save.html.erb
<%  if @camp.errors.any? %>
<div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning radius">
    <a href="#" class="close">&times;</a>
<h3><%= pluralize(@camp.errors.count, "error")%> prohibited this camp from being saved:</h3>
      <ul>
      <% @camp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
</div>
<% end %>

app/views/camps/_form.html.erb
<%= simple_form_for(@camp, html: { class: 'form-horizontal' }) do |f| %>
       
    <div class="row">
      <div class="small-6 columns">
        <h3><%= controller.action_name.capitalize %> Camp</h3>
        <%= f.input :curriculum_id, collection: Curriculum.active.alphabetical, prompt: "Select curriculum..." %>
        <%= f.input :cost %>
        <%= f.input :max_students %>
        <%= f.input :start_date, as: :date, order: [:month, :day, :year], include_blank: true, start_year: Date.today.year - 1, end_year: Date.today.year + 1 %>
        <%= f.input :end_date, as: :date, order: [:month, :day, :year], include_blank: true, start_year: Date.today.year - 1, end_year: Date.today.year + 1 %>
        <%= f.input :time_slot, collection: [['Morning','am'],['Afternoon','pm']], prompt: "Select time..." %>
        <%= f.input :location_id, collection: Location.active.alphabetical, prompt: "Select location..." %>
        <%= f.input :active,as: :radio_buttons %>
      </div>
      <div class="small-1 columns">&nbsp;</div>
      <div class="small-5 columns">
        <% if controller.action_name=="edit" && @camp.active %>
        <h3>Camp Instructor(s)</h3>
        <%= f.input :instructor_ids, label: "", collection: Instructor.active.alphabetical, as: :check_boxes %>
        <% end %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of camps', camps_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/camps/_inactive_camps.html.erb
<% if logged_in? %>
<% unless @inactive_camps.empty? %>
  <div class="panel clearfix">
    <h5>Inactive Camps</h5>
    <ul class="side-nav">
      <% @inactive_camps.each do |camp| %>
        <li><%= link_to camp.name, camp_path(camp) %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%end%>

app/views/camps/_past_camps.html.erb
<% if logged_in?%>

<% unless @inactive_camps.empty? %>
<h3>Past Camps</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>Time slot</th>
      <th>Max students</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @past_camps.each do |camp| %>
      <tr>
        <td><%= link_to camp.name,camp_path(camp) %></td>
        <td><%= camp.start_date.strftime('%m/%d/%y') %></td>
        <td><%= camp.time_slot=="am" ? "Morning" : "Afternoon" %></td>
        <td><%= camp.max_students %></td>
        <td><%= link_to 'Edit', edit_camp_path(camp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @past_camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>
<%end%>
<%end%>

app/views/camps/_upcoming_camps.html.erb
<h3>Upcoming Camps</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>Time slot</th>
      <th>Max students</th>
      <% if logged_in? && current_user.role == "admin" %>
      <th></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @upcoming_camps.each do |camp| %>
      <tr>
        <td><%= link_to camp.name,camp_path(camp) %></td>
        <td><%= camp.start_date.strftime('%m/%d/%y') %></td>
        <td><%= camp.time_slot=="am" ? "Morning" : "Afternoon" %></td>
        <td><%= camp.max_students %></td>
        <% if logged_in? && current_user.role == "admin" %>
        <td><%= link_to 'Edit', edit_camp_path(camp) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @upcoming_camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/camps/edit.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>Edit Camp</h1>
   	</div>
  </div>
</div>
<%=render 'cannot_save'%>
</br>

<div class="row">
<div class ="small-12 colums">
   	<%= render 'form' %>
</div>
</div>

app/views/camps/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "camp", 
                                                         primary: "upcoming_camps", 
                                                         secondary: "past_camps", 
                                                         sidebar: "inactive_camps"} %>

app/views/camps/new.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>New Camp</h1>
   	</div>
  </div>
</div>
<%=render 'cannot_save'%>
</br>
<div class="row">
<div class ="small-12 colums">
<%= render 'form' %>
</div>
</div>

app/views/camps/show.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-8 colums">
    <h1>Camp Details</h1>
    </div>
  </div>
</div>
<%= render :partial => "partials/flash" %>
<%= render :partial =>"cannot_save"%>
<div class="row">
  
  </br>
  <div class="small-6 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "camp_details" %>
  </div>

  <div class="small-6 columns ends">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'camp_instructors' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
<%= render partial: "partials/object_options", locals: {model_name: "camp", object: @camp}  %>
</div>
</div>