config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :sessions
  resources :users
  resources :locations
  resources :families
  resources :students
  resources :registrations
  resources :camp_instructors

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/financial', to: 'home#financial', as: :financial


  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  
  # set the root url
  root to: 'home#index'

end

app/views/partials/_cannot_save.html.erb
<%  if eval(this_object).errors.any? %>
<div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning radius">
    <a href="#" class="close">&times;</a>
<h6><%= pluralize((this_object).errors.count, "error" )%> prohibited this instructor from being saved:</h6>
<% this_object.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
</br>
<% end %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %> radius">
  	<%= msg %>
    <a href="#" class="close">&times;</a>
    
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer">
	
	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
    <%= link_to 'About Us', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
	<br /><br />
	<div id="copy">
		Webmaster: <%= mail_to("zying@andrew.cmu.edu", "Leo Ying", encode: "javascript") %> 
		&nbsp;&nbsp;&copy 2014
	</div>

</div>

app/views/partials/_index_structure.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1> <%= model_name.capitalize %></h1>
    </div>
  </div>
</div>
 <%= render :partial => "partials/flash" %>
</br>
<div class="row">
  <div class="small-7 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
<%if logged_in? && current_user.role == "admin"%>
   <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
  <i class="fa fa-plus"></i>
  &nbsp;Add a New <%= model_name.capitalize %>
<% end %>

    <%end%>
  </div>
  <div class="small-5 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

app/views/partials/_instructor_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <%= link_to(eval("#{model_name.pluralize}_path"), class: 'button radius') do %>
    <i class="fa fa-list"></i>
    &nbsp;Display All <%= model_name.pluralize.capitalize %>
  <% end %>
  &nbsp;&nbsp;
  <% if logged_in? %>

  <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button radius') do %>
    <i class="fa fa-pencil"></i>
    &nbsp;<%= "Edit this #{model_name}" %>
  <% end %>
  &nbsp;&nbsp;
  <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button radius alert') do %>
    <i class="fa fa-trash-o"></i>
    &nbsp;<%= "Delete #{model_name}" %>
  <% end %>
  <%end%>
</div>

app/views/partials/_nav.html.erb
<nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1 id="title"><%= link_to "A&M Chess Camp", home_path %></h1>
        </li>
      </ul>
      <section class="top-bar-section">

        <ul class="right">
          <% if logged_in? && current_user.role == "admin" %>
          <li class="active"><%=link_to "Families", families_path%></li>
          <li class="active"><%=link_to "Students", students_path%></li>
          <% end %>
          <li class="active"><%=link_to "Camps", camps_path%></li>
          <li class="active"><%=link_to "Instructors", instructors_path%></li>
          <li class="active"><%=link_to "Curriculum", curriculums_path%></li>
          <li class="active"><%=link_to "Locations", locations_path%></li>
      </section>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <%= link_to(eval("#{model_name.pluralize}_path"), class: 'button radius') do %>
    <i class="fa fa-list"></i>
    &nbsp;Display All <%= model_name.pluralize.capitalize %>
  <% end %>
  &nbsp;&nbsp;
  <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button radius') do %>
    <i class="fa fa-pencil"></i>
    &nbsp;<%= "Edit this #{model_name}" %>
  <% end %>
  &nbsp;&nbsp;
  <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button radius alert') do %>
    <i class="fa fa-trash-o"></i>
    &nbsp;<%= "Delete #{model_name}" %>
  <% end %>
</div>