config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :sessions
  resources :users
  resources :locations
  resources :families
  resources :students
  resources :registrations
  resources :camp_instructors

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/financial', to: 'home#financial', as: :financial


  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  
  # set the root url
  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@instructors=Instructor.active.alphabetical
  	@camps=Camp.active.upcoming.chronological
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def financial
    @camps=Camp.alphabetical.select { |e| e.start_date>Date.new(2014,1,1) && e.start_date<=Date.new(2014,12,31) }
  end
  
end

app/views/home/_general_home.html.erb
<div id ="pic">
  <%= render :partial => "partials/flash" %>
  <div class="row">
   <div class ="small-7 columns">
    <h1 class="welcome">Learn Chess </br>Better, Together</h1>
    <p id ="ad">
    Interested in Chess? Want to learn something in the summer?</br>
  Come to A&M Chess Camp. You will certainly get a nice </br>
  experience at A&M with friends, chess and much more.
  </p>
   </div>
   <div class ="small-1 column">
    &nbsp;
   </div>
      <div class ="small-4 columns">
    <div class="row">
      <div class ="small-1 column">
    &nbsp;
   </div>
  <div class="small-11 columns">
    <h4 class="welcome">Log In</h4>
    <%= form_tag sessions_path do %>
        <%= text_field_tag :username, params[:username] ,:placeholder=>"Username"%>
        <%= password_field_tag :password%>
    <%= submit_tag "Log In" ,class: 'button radius'%>
    <% end %>
  </div>
   </div>
 </div>
	</br>
  <div class="row">
   <div class ="small-7 columns">
   	
   </div>
  </div>
</div>
</div>

app/views/home/_personal_home.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-7 columns">
    <h1>Welcome back, <%= current_user.instructor.first_name%></h1>
    </div>
    <div class ="small-1 columns ends">
    </br>
      </br>
      <%=link_to image_tag('logout.png'), logout_path,id:"logout"%>
    </div>
  </div>
</div>
<div>
  <%= render :partial => "partials/flash" %>
</div>

</br>
<div class="row">
  <div class ="small-3 columns">
  </br>
    <% if current_user.instructor.picture_url.nil? %>
    <%= image_tag 'picture_placeholder.jpg' %>
    <%else %>
    <%= image_tag current_user.instructor.picture_url %>
    <%end%>
    </br>
  </br>
    <p>
      <strong>Phone:</strong> 
    </br>
        <%= number_to_phone(current_user.instructor.phone) %>
    </p>
    <p>
      <strong>Email:&nbsp;</strong> 
        <%= mail_to current_user.instructor.email, current_user.instructor.email, encode: "javascript" %>
    </p>

    <p>
      <strong>Biography</strong><br />
        <%= current_user.instructor.bio.nil? ? "N/A" : current_user.instructor.bio %>
      </p>
    <%= link_to 'Edit Profile ', edit_instructor_path(current_user.instructor),class:"button expand"%><% if logged_in? && current_user.role == "admin" %> 
    <%= link_to 'Financial Report', financial_path %>
    <%end%>
  </div>

  <div class ="small-9 columns">
  <div class="row">
    <div class ="small-12 columns">
    <h3>My Camps</h3>
      <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Time Slot</th>
        <th>Registration Number</th>
        <th>Location</th>
        <th>Average Rating</th>
      </tr>
    </thead>

    <tbody>
      <% current_user.instructor.camps.each do |camp| %>
        <tr>
          <td><%= link_to camp.name,camp_path(camp) %></td>
          <td><%= camp.start_date.strftime('%m/%d/%y') %></td>
          <td><%= camp.end_date.strftime('%m/%d/%y') %></td>
          <td><%= camp.time_slot=="am" ? "Morning" : "Afternoon" %></td>
          <td><%= camp.registrations.count %></td>
          <td><%= link_to camp.location.name, location_path(camp.location) %></td>
          <td><%= (camp.students.map { |e| e.rating }.reduce(:+).to_f / camp.registrations.count).round(2)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
<% if logged_in? && current_user.role == "admin" %>
<div class="row">
<div class="small-7 columns">
   <h3>Instructor Assignments</h3>
    <table>
      <thead>
        <th>Instructor</th>
        <th>Camps Assigned</th>
      </thead>
      <tbody>
        <% @instructors.each do |ins| %>
        <tr>
          <td><%=ins.name%></td>
          <td><% ins.camps.upcoming.active.alphabetical.each do |camp| %>
            <li>
            <%=link_to camp.name, camp_path(camp) %>
            (<%=camp.start_date.strftime('%m/%d/%y')%>)
            <li>
            <%end%>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>
  <div class="small-5 columns">
    <h3>Camp Registrations</h3>
    <table>
      <thead>
          <th>Camp</th>
          <th>Paid</th>
          <th>Deposit</th>
      </thead>
      <tbody>
        <% @camps.each do |camp| %>
        <tr>
          <td><%=link_to camp.name, camp_path(camp)%> 
          </br>(<%=camp.start_date.strftime('%m/%d/%y')%>)</td>
          <td><%=camp.registrations.paid.count%></td>
          <td><%=camp.registrations.deposit_only.count%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>
<%end%>

app/views/home/about.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>About</h1>
   	</div>
  </div>
</div>
</br>
<div class="row">
<div class ="small-12 colums">
   	<p>	<div id="about_pic"><%= image_tag 'team_wins_5th.jpg', class: "left" %></div>
	We love chess. 	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</p>
</div>
</div>

app/views/home/contact.html.erb
	<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>Contact Us</h1>
   	</div>
  </div>
</div>
</br>
<div class="row">
<div class ="small-12 colums">
   	<p><div id="profile"><%= image_tag 'portrait.jpg' %></div>Unfortunately, the A&M Chess Camp is not a real website, but rather a 
	sample project for programming students at Carnegie Mellon University. We 
	are sure that you wanted good chess instrusction.  If you are 
	bitterly disappointed (and quite honestly, you should be) and want to 
	grouse to someone, here's the contact info:</p>

<table cellpadding="3">
	<tr>
		<td>Webmaster:&nbsp;&nbsp;&nbsp;</td>
		<td>Leo Ying</td>
	</tr>
	<tr>
		<td>Email:</td>
		<td>
		<%= mail_to("zying@andrew.cmu.edu", "Leo Ying*", encode: "javascript") %> 
		</td>
	</tr>
	<tr>
		<td>Phone:</td>
		<td>123-456-7890</td>
	</tr>
</table>

<p class="note"><br>I am a Information Systems sophomore at Carnegie Mellon University
	<br><br><em>I am right-handed but I rode my bike with my left hand</em></p>

</div>
</div>

app/views/home/financial.html.erb
 <div id ="pic1">
  <div class="row">
   <div class ="small-8 colums">
     <h1>Financial Report for A&M Chess Camp</h1>
    </div>
  </div>
</div>
</br>
 <div class="row">
    <div class ="small-8 columns">
      <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Amount Received</th>
        <th>Amount Due</th>
      </tr>
    </thead>

    <tbody>
      <% @camps.each do |camp| %>
        <tr>
          <td><%= link_to camp.name,camp_path(camp) %> (<%= camp.start_date.strftime('%m/%d/%y') %>)</td>
          <td><%= camp.registrations.paid.count*camp.cost + camp.registrations.deposit_only.count* 50%></td>
          <td><%= camp.registrations.deposit_only.count*(camp.cost-50) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class ="small-4 columns">
  <h3>Total Payment Received: $<%=@camps.map { |e| e.registrations.paid.count*e.cost }.sum + @camps.map { |e| e.registrations.deposit_only.count*50 }.sum%></h3> 
  <h3 style="color:red;">Total Payment Due: $<%=@camps.map { |e| e.registrations.deposit_only.count*e.cost }.sum-@camps.map { |e| e.registrations.deposit_only.count*50 }.sum%></h3>
  <p>-------------------------------------------------------</p>
  <h2>Total: $<%=@camps.map { |e| e.registrations.count*e.cost}.sum%></h2>
</div>
</div>

app/views/home/index.html.erb
<% if logged_in? %>
	<%= render :partial => 'personal_home' %>
<% else %>
	<%= render :partial => 'general_home' %>
<% end %>

app/views/home/privacy.html.erb
<div id ="pic1">
  <div class="row">
   <div class ="small-6 colums">
    <h1>Privacy</br> Policy</h1>
   	</div>
  </div>
</div>
</br>
<div class="row">
<div class ="small-12 colums">
A&M Chess Camp is committed to protecting the privacy of confidential information submitted through our web sites by employees, students, and visitors. The purpose of this privacy statement is to inform you regarding which personal or personally identifiable information we may collect from you when you visit our websites, as well as how we use such information. 

Information About You
We collect information about you from our web sites through:
Web Logs and Cookies:  Our web servers generate temporary logs and cookies that contain a variety of information about each user and his/her use of our web sites.  The data that we collect helps us respond to user requests in an appropriate and/or personalized manner.
Online Forms:  We hosts numerous online forms through which it collects user information.  This information helps us serve its users more efficiently. Delivery of the service supported by an online form may require that we share information with external business partners.  In any such case, the external business partner will be contractually required to honor our commitment to the privacy of that information.
Online Surveys:  There are typically numerous online surveys being conducted on our web sites. Person(s) responsible for conducting online surveys that collect personally identifiable information should clearly state at the survey site the extent to which any information provided will be shared. Data from surveys may be shared with external third parties in ways that do not compromise privacy.
</p>
</div>
</div>

app/views/home/search.html.erb
<h2>Search result for term <em>'<%= @query %>'</em> resulted in <%= pluralize(@total_hits, 'hit') %></h2>
<p class="supertiny">&nbsp;</p>

<% unless @owners.empty? %>
	<p><em><strong>Owners matching term '<%= @query %>'</strong></em></p>
	<ul>
		<% for owner in @owners do %>
			<li><%= link_to owner.name, owner_path(owner) %></li>
		<% end %>
	</ul>
	<p class="smtext">&nbsp;</p>
<% end %>

<% unless @pets.empty? %>
	<p><em><strong>Pets matching term '<%= @query %>'</strong></em></p>
	<ul>
		<% for pet in @pets do %>
			<li><%= link_to pet.name, pet_path(pet) %>: owned by <%= "#{pet.owner.name}" %></li>
		<% end %>
	</ul>
	<p class="supertiny">&nbsp;</p>
<% end %>